# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: 'Performance test'
on:
  # we can manually trigger this workflow by using dispatch for debugging
  repository_dispatch:
    types: [trigger-perf]
  workflow_dispatch:
    inputs:
      sha:
        description: 'the commit hash to benchmark'
        required: true
    
env:
  TF_VAR_aws_access_key_id: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
  TF_VAR_aws_secret_access_key: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}
  GH_PAGES_BRANCH: gh-pages-temp
  MAX_BENCHMARKS_TO_KEEP: 100
  COMMIT_USER: Github Actions
  COMMIT_EMAIL: actions@github.com
  
jobs:
  upload-performance-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
      
      - name: Install Jinja2
        run: pip install Jinja2
          
      - name: Produce performance report
        run: python e2etest/get-performance-model-table.py v0.15.1

      - name: Store benchmark result
        uses: jefchien/github-action-benchmark@v1.11.12-alpha2
        with:
          tool: "customSmallerIsBetter"
          output-file-path: performance-data.json
          benchmark-data-dir-path: benchmark/trend
          max-items-in-chart: ${{ env.MAX_BENCHMARKS_TO_KEEP }}
          gh-pages-branch: ${{ env.GH_PAGES_BRANCH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-sha: ${{ github.event.inputs.sha }}
          auto-push: false

      - name: Commit to gh-pages branch
        run: |
          git switch ${{ env.GH_PAGES_BRANCH }}
          rsync -avv performance-report.md benchmark/report.md
          rsync -avv performance-data.json benchmark/data/
          git add benchmark/data/* benchmark/report.md
          git -c user.name="${{ env.COMMIT_USER }}" -c user.email="${{ env.COMMIT_EMAIL }}" commit --amend --reset-author -m "Update benchmarking for ${{ github.event.inputs.sha }}"
          git push origin ${{ env.GH_PAGES_BRANCH }}:${{ env.GH_PAGES_BRANCH }}
