# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: 'Performance test'
on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Skip second test'
        required: false
        type: boolean
  
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test == 'false' }}
    steps:
      - run: echo "test"
  test2:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test == 'true' }}
    steps:
      - run: echo "test 2"
  check-all:
    runs-on: ubuntu-latest
    needs: [test, test2]
    if: |
      always() &&
      (needs.test.result == 'success' || needs.test.result == 'skipped') &&
      (needs.test2.result == 'success' || needs.test2.result == 'skipped')
    steps:
      - run: echo "all test passed"
  test3:
    runs-on: ubuntu-latest
    needs: [check-all]
    if: always() && needs.check-all.result == 'success'
    steps:
      - run: echo "${{ needs.check-all.result }}"
